version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - crypto-network
    depends_on:
      - backend-service
      - mysqldb

  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - crypto-network
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_NAME=crypto_db
      - DB_USER=root
      - DB_PASSWORD=123456

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crypto_db
    ports:
      - "3306:3306"
    networks:
      - crypto-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  crypto-network:
    driver: bridge

volumes:
  mysql_data: