replicaCount: 1

image:
  repository: mysql
  tag: "5.7"

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

mysqlRootPassword: "123456"
mysqlDatabase: "crypto_db"
mysqlUser: "USER"
mysqlPassword: "123456"

persistence:
  enabled: false
